version: "3.8"

services:
  postgres:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=fiap-fastfood
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  mongo-product:
    image: mongo:latest
    ports:
      - "27017:27017"
    volumes:
      - mongo-product-data:/data/db

  web:
    build:
      context: .
      dockerfile: Dockerfile-web
    restart: unless-stopped
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres:5432/fiap-fastfood
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
      - MONGO_PRODUCT_URL=mongodb://mongo-product:27017/products
    depends_on:
      - postgres
      - mongo-product

  postgres-payment:
    image: postgres:14.4
    environment:
      - POSTGRES_DB=fiap-fastfood-payment
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=root
    ports:
      - "5433:5432"
    volumes:
      - postgres-payment-data:/var/lib/postgresql/data

  payment-service:
    build:
      context: .
      dockerfile: Dockerfile-payment
    ports:
      - "8082:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://postgres-payment:5433/fiap-fastfood-payment
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=root
    depends_on:
      - postgres-payment

  producao-service:
    build:
      context: .
      dockerfile: Dockerfile-production
    ports:
      - "8083:8080"
    environment:
      - MONGO_DB_URL=mongodb://mongo-product:27017/products
    depends_on:
      - mongo-product

volumes:
  postgres-data:
  mongo-product-data:
  postgres-payment-data:
