name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


    - run: git clone https://github.com/fiap-fast-food/k8s-terraform.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=k8s-terraform/env/Homolog init

    - run: terraform -chdir=k8s-terraform/env/Homolog apply -auto-approve

    - run: echo "$(terraform -chdir=k8s-terraform/env/Homolog output -raw IP_db)"
      id: URL

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - run: aws sts get-caller-identity

    - run: aws eks update-kubeconfig --region us-east-2 update-kubeconfig --name fiap-food-api
    
    - run: kubectl get svc

    - run: kubctl create secret generic datasource_url --from-literal=HOST=${{steps.URL.output.stdout}}:${{secrets.DBPORT}}/${{secrets.DBNAME}}
    - run: kubctl create secret generic datasource_username --from-literal=USER=${{secrets.SPRING_DATASOURCE_USERNAME}}
    - run: kubctl create secret generic datasource_password --from-literal=PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}
    - run: kubctl create secret generic datasource_driver_class_name --from-literal=DRIVER_CLASS_NAME=${{secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME}}
    - run: kubctl create secret generic dbport --from-literal=DBPORT=${{secrets.DBPORT}}
    - run: kubctl create secret generic dbname --from-literal=DBNAME=${{secrets.DBNAME}}
    - run: kubctl create secret generic api_payment --from-literal=HOST_API_PAYMENT=${{secrets.API_PAYMENT_URL}}

    - run: kubectl apply -f k8s-terraform/java.yml
