name: kubernetes

on:
  workflow_call:

jobs:

  EKS:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v3

    - name: configurando credenciais da AWS
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        aws-region: us-east-2


    - run: git clone https://github.com/fiap-fast-food/k8s-terraform.git

    - name: HashiCorp - Setup Terraform
      uses: hashicorp/setup-terraform@v2.0.3
      
    - run: terraform -chdir=k8s-terraform/src init

    - run: terraform -chdir=k8s-terraform/src apply -auto-approve

  #  - run: echo "$(terraform -chdir=k8s-terraform/env/Homolog output -raw IP_db)"
   #   id: URL

    - name: Kubectl tool installer
      uses: Azure/setup-kubectl@v3

    - run: aws sts get-caller-identity

    - run: aws eks --region us-east-2 update-kubeconfig --name fiap-food-api-cluster
    
    - run: kubectl get svc

    - run: kubectl delete secret datasource_url --ignore-not-found
    - run: kubectl create secret generic datasource_url --from-literal=HOST=${{ steps.URL.outputs.stdout }}:${{secrets.DBPORT}}/${{secrets.DBNAME}}
    
    - run: kubectl delete secret datasource_username --ignore-not-found
    - run: kubectl create secret generic datasource_username --from-literal=USER=${{secrets.SPRING_DATASOURCE_USERNAME}}
    
    - run: kubectl delete secret datasource_password --ignore-not-found
    - run: kubectl create secret generic datasource_password --from-literal=PASSWORD=${{secrets.SPRING_DATASOURCE_PASSWORD}}
    
    - run: kubectl delete secret datasource_driver_class_name --ignore-not-found
    - run: kubectl create secret generic datasource_driver_class_name --from-literal=DRIVER_CLASS_NAME=${{secrets.SPRING_DATASOURCE_DRIVER_CLASS_NAME}}
    
    - run: kubectl delete secret dbport --ignore-not-found
    - run: kubectl create secret generic dbport --from-literal=DBPORT=${{secrets.DBPORT}}
    
    - run: kubectl delete secret dbname --ignore-not-found
    - run: kubectl create secret generic dbname --from-literal=DBNAME=${{secrets.DBNAME}}
    
    - run: kubectl delete secret api_payment --ignore-not-found
    - run: kubectl create secret generic api_payment --from-literal=HOST_API_PAYMENT=${{secrets.API_PAYMENT_URL}}

    - run: kubectl apply -f k8s-terraform/src/java.yml

    - run: kubectl set image deployment/fiap-food-api fiap-food-api-container=fiapfastfood/fiap-api:${{ github.event.pull_request.number }}
